### ISSUE TITLE
waf bulid fail. Raise DsdlCompilerException(str(text))

### ISSUE THREAD

**Issue by LeiOuYang** [ArduPilot/ardupilot#11417]
#### Version
master: copter version--3.7.0dev

#### Airframe type
octa

#### Hardware type
Pixhawk1

#### Logs

Found 222 MAVLink message types in 4 XML files
Generating C implementation in directory /cygdrive/c/ardupilot/build/Pixhawk1/libraries/GCS_MAVLink/include/mavlink/v2.0/ardupilotmega
Compiler failure
Traceback (most recent call last):
  File "/cygdrive/c/ardupilot/modules/uavcan/libuavcan/dsdl_compiler/libuavcan_dsdlc", line 61, in <module>
    dsdlc_run(args.source_dir, args.incdir, args.outdir)
  File "/cygdrive/c/ardupilot/modules/uavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 63, in run
    run_generator(types, output_dir)
  File "/cygdrive/c/ardupilot/modules/uavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 112, in run_generator
    die(ex)
  File "/cygdrive/c/ardupilot/modules/uavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 90, in die
    raise DsdlCompilerException(str(text))
DsdlCompilerException: line 16, col 17: invalid syntax (, line 1)
line 16, col 17: invalid syntax (, line 1)

uavcangen returned 1 error code
Generating C implementation in directory /cygdrive/c/ardupilot/build/Pixhawk1/libraries/GCS_MAVLink/include/mavlink/v2.0/common
Generating C implementation in directory /cygdrive/c/ardupilot/build/Pixhawk1/libraries/GCS_MAVLink/include/mavlink/v2.0/uAvionix
Generating C implementation in directory /cygdrive/c/ardupilot/build/Pixhawk1/libraries/GCS_MAVLink/include/mavlink/v2.0/icarous
Copying fixed headers for protocol 2.0 to /cygdrive/c/ardupilot/build/Pixhawk1/libraries/GCS_MAVLink/include/mavlink/v2.0
Waf: Leaving directory `/cygdrive/c/ardupilot/build/Pixhawk1'
Build failed
 -> task in 'uavcan' failed (exit status 1):
        {task 7696522639792: uavcangen com,uavcan -> }
 (run with -v to display more information)

**Comment by LeiOuYang** [comment]
Python upgrade to version 3.6, problem solving
