### ISSUE TITLE
ArduCopter approaches too near fence in Avoidance mode

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#11525]
### Bug report

**Issue details**

Copter's Avoidance is supposed to stop at some margin in from the fence.  However, when the margin is specified as 3m the vehicle ends up 30cm from the fence radius when in slide mode, and doesn't reach the margin when in stop mode.

Copter's `HorizontalAvoidFence` autotest shows this problem in its stdout:

Slide mode:
```
AUTOTEST: Drained 0 messages from mav (0.000000/s)
AUTOTEST: Push: distance=14.705458 11.000000<want<13.000000
AUTOTEST: Drained 0 messages from mav (0.000000/s)
AUTOTEST: Push: distance=14.716589 11.000000<want<13.000000
AUTOTEST: Drained 4 messages from mav (4211.148594/s)
AUTOTEST: Push: distance=14.716589 11.000000<want<13.000000
AUTOTEST: Drained 0 messages from mav (0.000000/s)
AUTOTEST: Push: distance=14.716589 11.000000<want<13.000000
AUTOTEST: Drained 0 messages from mav (0.000000/s)
AUTOTEST: Push: distance=14.716589 11.000000<want<13.000000
AUTOTEST: Drained 0 messages from mav (0.000000/s)
AUTOTEST: Push: distance=14.705458 11.000000<want<13.000000
AUTOTEST: Drained 0 messages from mav (0.000000/s)
AUTOTEST: Push: distance=14.716644 11.000000<want<13.000000
AUTOTEST: Drained 25 messages from mav (1050.014520/s)
AUTOTEST: Push: distance=14.716644 11.000000<want<13.000000
AUTOTEST: Drained 0 messages from mav (0.000000/s)
AUTOTEST: Push: distance=14.705512 11.000000<want<13.000000
AUTOTEST: Push time up
AUTOTEST: Exception caught: Traceback (most recent call last):
  File "/home/pbarker/rc/ardupilot/Tools/autotest/common.py", line 1849, in run_one_test
    test_function()
  File "/home/pbarker/rc/ardupilot/Tools/autotest/arducopter.py", line 624, in fly_fence_avoid_test
    raise NotAchievedException("Failed max")
NotAchievedException: Failed max
```

Stop mode:
```
AUTOTEST: Distance from home: now=10.753469 12.000000<want<20.000000
AUTOTEST: Distance from home: now=10.775733 12.000000<want<20.000000
AUTOTEST: Distance from home: now=10.820261 12.000000<want<20.000000
AUTOTEST: Exception caught: Traceback (most recent call last):
  File "/home/pbarker/rc/ardupilot/Tools/autotest/common.py", line 1849, in run_one_test
    test_function()
  File "/home/pbarker/rc/ardupilot/Tools/autotest/arducopter.py", line 630, in fly_fence_avoid_test
    self.fly_fence_avoid_test_radius_check(avoid_behave=1, timeout=timeout)
  File "/home/pbarker/rc/ardupilot/Tools/autotest/arducopter.py", line 594, in fly_fence_avoid_test_radius_check
    self.wait_distance_from_home(12, 20)
  File "/home/pbarker/rc/ardupilot/Tools/autotest/arducopter.py", line 562, in wait_distance_from_home
    raise NotAchievedException("Did not achieve distance from home")
NotAchievedException: Did not achieve distance from home
```

**Version**

master

**Platform**
[  ] All
[  ] AntennaTracker
[ X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**

SITL default

**Hardware type**

SITL

**Logs**

**Comment by andyp1per** [comment]
The copter issue is a red-herring - the timeout just needs to be longer - the copter slows as it approaches the margin so takes a while to actually get to the margin
