### ISSUE TITLE
Unable to build on Ubuntu with python 3.8.6

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#15838]
## Bug report

Clean git clone, won't build /make SITL run,

**Version**
Current master

**Platform**
[  ] All
[  ] AntennaTracker
[x ] Copter
[ x] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
n/a
**Hardware type**

SITL

**Logs**

```
$ sim_vehicle.py -v ArduPlane --console --map
SIM_VEHICLE: Start
SIM_VEHICLE: Killing tasks
SIM_VEHICLE: Starting up at SITL location
SIM_VEHICLE: WAF build
SIM_VEHICLE: Configure waf
SIM_VEHICLE: "/home/andre/prog/ardupilot/modules/waf/waf-light" "configure" "--board" "sitl"
Setting top to                           : /home/andre/prog/ardupilot 
Setting out to                           : /home/andre/prog/ardupilot/build 
Autoconfiguration                        : enabled 
Setting board to                         : sitl 
Using toolchain                          : native 
Checking for 'g++' (C++ compiler)        : /usr/lib/ccache/g++ 
Checking for 'gcc' (C compiler)          : /usr/lib/ccache/gcc 
Checking for c flags '-MMD'              : yes 
Checking for cxx flags '-MMD'            : yes 
CXX Compiler                             : g++ 10.2.0 
Checking for need to link with librt     : not necessary 
Checking for feenableexcept              : yes 
Checking for HAVE_CMATH_ISFINITE         : yes 
Checking for HAVE_CMATH_ISINF            : yes 
Checking for HAVE_CMATH_ISNAN            : yes 
Checking for NEED_CMATH_ISFINITE_STD_NAMESPACE : yes 
Checking for NEED_CMATH_ISINF_STD_NAMESPACE    : yes 
Checking for NEED_CMATH_ISNAN_STD_NAMESPACE    : yes 
Checking for header endian.h                   : yes 
Checking for header byteswap.h                 : yes 
Checking for HAVE_MEMRCHR                      : yes 
Checking for program 'python'                  : /usr/bin/python 
Checking for python version >= 2.7.0           : 3.8.6 
Checking for program 'python'                  : /usr/bin/python 
Checking for python version >= 2.7.0           : 3.8.6 
Source is git repository                       : yes 
Update submodules                              : yes 
Checking for program 'git'                     : /usr/bin/git 
Checking for program 'size'                    : /usr/bin/size 
Benchmarks                                     : disabled 
Unit tests                                     : enabled 
Scripting                                      : enabled 
Scripting runtime checks                       : enabled 
Checking for program 'rsync'                   : /usr/bin/rsync 
'configure' finished successfully (0.782s)
SIM_VEHICLE: Building
SIM_VEHICLE: "/home/andre/prog/ardupilot/modules/waf/waf-light" "build" "--target" "bin/arduplane"
Waf: Entering directory `/home/andre/prog/ardupilot/build/sitl'
Embedding file models/Callisto.json:Tools/autotest/models/Callisto.json
[6/7] Processing uavcangen: libraries/AP_UAVCAN/dsdl/ardupilot libraries/AP_UAVCAN/dsdl/com
Internal error
Traceback (most recent call last):
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 714, in parse
    return self.parse_source(filename, source_text)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 706, in parse_source
    raise ex
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 672, in parse_source
    raise ex
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 659, in parse_source
    attr = self._parse_line(filename, tokens)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 618, in _parse_line
    attrtype = self._parse_type(filename, typename, cast_mode)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 580, in _parse_type
    return self._parse_compound_type(filename, typedef)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 550, in _parse_compound_type
    definition_filename = self._locate_compound_type_definition(filename, typedef)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 477, in _locate_compound_type_definition
    directories = locate_namespace_directories(namespace)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 468, in locate_namespace_directories
    error('Unknown namespace [%s]', ns)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 723, in error
    raise DsdlException(fmt % args)
uavcan.dsdl.common.DsdlException: /home/andre/prog/ardupilot/libraries/AP_UAVCAN/dsdl/ardupilot/equipment/trafficmonitor/20790.TrafficReport.uavcan:2: Unknown namespace [uavcan]
Compiler failure
Traceback (most recent call last):
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 714, in parse
    return self.parse_source(filename, source_text)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 706, in parse_source
    raise ex
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 672, in parse_source
    raise ex
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 659, in parse_source
    attr = self._parse_line(filename, tokens)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 618, in _parse_line
    attrtype = self._parse_type(filename, typename, cast_mode)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 580, in _parse_type
    return self._parse_compound_type(filename, typedef)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 550, in _parse_compound_type
    definition_filename = self._locate_compound_type_definition(filename, typedef)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 477, in _locate_compound_type_definition
    directories = locate_namespace_directories(namespace)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 468, in locate_namespace_directories
    error('Unknown namespace [%s]', ns)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 723, in error
    raise DsdlException(fmt % args)
uavcan.dsdl.common.DsdlException: /home/andre/prog/ardupilot/libraries/AP_UAVCAN/dsdl/ardupilot/equipment/trafficmonitor/20790.TrafficReport.uavcan:2: Unknown namespace [uavcan]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andre/prog/ardupilot/modules/uavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 94, in run_parser
    types = dsdl.parse_namespaces(source_dirs, search_dirs)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 871, in parse_namespaces
    t = parser.parse(filename)
  File "/home/andre/.local/lib/python3.8/site-packages/uavcan/dsdl/parser.py", line 719, in parse
    raise DsdlException('Internal error: %s' % str(ex), file=filename)
uavcan.dsdl.common.DsdlException: /home/andre/prog/ardupilot/libraries/AP_UAVCAN/dsdl/ardupilot/equipment/trafficmonitor/20790.TrafficReport.uavcan: Internal error: /home/andre/prog/ardupilot/libraries/AP_UAVCAN/dsdl/ardupilot/equipment/trafficmonitor/20790.TrafficReport.uavcan:2: Unknown namespace [uavcan]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andre/prog/ardupilot/modules/uavcan/libuavcan/dsdl_compiler/libuavcan_dsdlc", line 61, in <module>
    dsdlc_run(args.source_dir, args.incdir, args.outdir)
  File "/home/andre/prog/ardupilot/modules/uavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 58, in run
    types = run_parser(source_dirs, include_dirs + source_dirs)
  File "/home/andre/prog/ardupilot/modules/uavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 97, in run_parser
    die(ex)
  File "/home/andre/prog/ardupilot/modules/uavcan/libuavcan/dsdl_compiler/libuavcan_dsdl_compiler/__init__.py", line 90, in die
    raise DsdlCompilerException(str(text))
libuavcan_dsdl_compiler.DsdlCompilerException: /home/andre/prog/ardupilot/libraries/AP_UAVCAN/dsdl/ardupilot/equipment/trafficmonitor/20790.TrafficReport.uavcan: Internal error: /home/andre/prog/ardupilot/libraries/AP_UAVCAN/dsdl/ardupilot/equipment/trafficmonitor/20790.TrafficReport.uavcan:2: Unknown namespace [uavcan]
/home/andre/prog/ardupilot/libraries/AP_UAVCAN/dsdl/ardupilot/equipment/trafficmonitor/20790.TrafficReport.uavcan: Internal error: /home/andre/prog/ardupilot/libraries/AP_UAVCAN/dsdl/ardupilot/equipment/trafficmonitor/20790.TrafficReport.uavcan:2: Unknown namespace [uavcan]

uavcangen returned 1 error code
Waf: Leaving directory `/home/andre/prog/ardupilot/build/sitl'
Build failed
 -> task in 'uavcan' failed (exit status 1): 
	{task 140654078360592: uavcangen ardupilot,com -> }
 (run with -v to display more information)
SIM_VEHICLE: Build failed
SIM_VEHICLE: Killing tasks

```

**Comment by AndKe** [comment]
My bad - I failed to use --recursive in git submodule update --init --recursive
