### ISSUE TITLE
No module named zlib

### ISSUE THREAD

**Issue by furkanozdemi** [ArduPilot/ardupilot#20164]
I have a problem.Please help me.

Waf: Entering directory `/home/furkan/ardupilot/build/sitl'
Traceback (most recent call last):
  File "/home/furkan/ardupilot/modules/waf/waflib/Scripting.py", line 158, in waf_entry_point
    run_commands()
  File "/home/furkan/ardupilot/modules/waf/waflib/Scripting.py", line 251, in run_commands
    ctx = run_command(cmd_name)
  File "/home/furkan/ardupilot/modules/waf/waflib/Scripting.py", line 235, in run_command
    ctx.execute()
  File "Tools/ardupilotwaf/ardupilotwaf.py", line 202, in execute
    return execute_method(self)
  File "/home/furkan/ardupilot/modules/waf/waflib/Scripting.py", line 573, in execute
    return execute_method(self)
  File "/home/furkan/ardupilot/modules/waf/waflib/Build.py", line 231, in execute
    self.execute_build()
  File "/home/furkan/ardupilot/modules/waf/waflib/Build.py", line 244, in execute_build
    self.recurse([self.run_dir])
  File "/home/furkan/ardupilot/modules/waf/waflib/Context.py", line 286, in recurse
    user_function(self)
  File "/home/furkan/ardupilot/wscript", line 765, in build
    _load_pre_build(bld)
  File "/home/furkan/ardupilot/wscript", line 749, in _load_pre_build
    brd.pre_build(bld)
  File "Tools/ardupilotwaf/boards.py", line 415, in pre_build
    self.embed_ROMFS_files(bld)
  File "Tools/ardupilotwaf/boards.py", line 429, in embed_ROMFS_files
    import embed
  File "Tools/ardupilotwaf/embed.py", line 10, in <module>
    import os, sys, tempfile, gzip
  File "/usr/local/lib/python2.7/gzip.py", line 9, in <module>
    import zlib
ImportError: No module named zlib
SIM_VEHICLE: Build failed
SIM_VEHICLE: Killing tasks

**Comment by hendjoshsr71** [comment]
Closing this is likely not an Issue. You should open a page on https://discuss.ardupilot.org/c/development-team/5 first and then if there is an issue found we can reopen this.

Sorry to be strict but otherwise our _Issue List_ would grow to unmanageable sizes. 

Reposting this here from the same exact wiki issue you made, https://github.com/ArduPilot/ardupilot_wiki/issues/4155

Your Python Version is 2.7 you should use python3 : Your command python is pointing to python2
Did you try installing the missing module zlib for python2?

Is this a recent install? If you used our install scripts you should not need to prepend the command with python as the ardupilot folder should be on the PATH.
