### ISSUE TITLE
Unable to complete vagrant setup (pymavlink)

### ISSUE THREAD

**Issue by atownnoob** [ArduPilot/ardupilot#21586]
bionic64: Collecting pymavlink
    bionic64:   Downloading pymavlink-2.4.34.tar.gz (10.6 MB)
    bionic64:   Installing build dependencies: started
    bionic64:   Installing build dependencies: finished with status 'done'
    bionic64:   Getting requirements to build wheel: started
    bionic64:   Getting requirements to build wheel: finished with status 'error'
    bionic64:   ERROR: Command errored out with exit status 1:
    bionic64:    command: /usr/bin/python /home/vagrant/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpjKoh9h
    bionic64:        cwd: /tmp/pip-install-52VoQ2/pymavlink
    bionic64:   Complete output (16 lines):
    bionic64:   Traceback (most recent call last):
    bionic64:     File "/home/vagrant/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
    bionic64:       main()
    bionic64:     File "/home/vagrant/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
    bionic64:       json_out['return_val'] = hook(**hook_input['kwargs'])
    bionic64:     File "/home/vagrant/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
    bionic64:       return hook(config_settings)
    bionic64:     File "/tmp/pip-build-env-mw4XbY/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
    bionic64:       return self._get_build_requires(config_settings, requirements=['wheel'])
    bionic64:     File "/tmp/pip-build-env-mw4XbY/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
    bionic64:       self.run_setup()
    bionic64:     File "/tmp/pip-build-env-mw4XbY/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
    bionic64:       exec(compile(code, __file__, 'exec'), locals())
    bionic64:     File "setup.py", line 108, in <module>
    bionic64:       with open("README.md", "r", encoding = "utf-8") as fh:
    bionic64:   TypeError: 'encoding' is an invalid keyword argument for this function
    bionic64:   ----------------------------------------
    bionic64: ERROR: Command errored out with exit status 1: /usr/bin/python /home/vagrant/.local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpjKoh9h Check the logs for full command output.

**Comment by atownnoob** [comment]
Apologies that I haven't followed the contributing guidelines. Next item will be in accordance with the guidelines.
To put a small summary - I have been following the technical documents for Windows SITL (https://ardupilot.org/dev/docs/setting-up-sitl-using-vagrant.html). Issue occurs at Step 4, "vagrant up". Unable to complete the environment build, with the issue listed above.

**Comment by atownnoob** [comment]
Closed, issue as described in pymavlink bug: https://github.com/ArduPilot/pymavlink/pull/724
