### ISSUE TITLE
WAF: unable to build on Python 3.11.2 

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/ardupilot#23663]
## Bug report

**Issue details**

Building on current Ubuntu 23.04 release (Debian based)

**Version**
master

**Platform**
[x ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
n/a

**Hardware type**
n/a

**Logs**
```
andre@Loke:~/prog/ardupilot$ ./waf 
Traceback (most recent call last):
  File "/home/andre/prog/ardupilot/modules/waf/waf-light", line 167, in <module>
    Scripting.waf_entry_point(cwd, VERSION, wafdir)
  File "/home/andre/prog/ardupilot/modules/waf/waflib/Scripting.py", line 80, in waf_entry_point
    env.load(os.path.join(cur, Options.lockfile))
  File "/home/andre/prog/ardupilot/modules/waf/waflib/ConfigSet.py", line 315, in load
    code = Utils.readf(filename, m='rU')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andre/prog/ardupilot/modules/waf/waflib/Utils.py", line 231, in readf
    with open(fname, m) as f:
         ^^^^^^^^^^^^^^
ValueError: invalid mode: 'rUb'
andre@Loke:~/prog/ardupilot$ 

```

**Comment by peterbarker** [comment]
Fixed by https://github.com/ArduPilot/ardupilot/pull/23651

**Comment by AndKe** [comment]
@peterbarker  - I tried - but got the same error, at the same line:

```
andre@Loke:~/prog/ardupilot$ git pull origin master
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 338 bytes | 338.00 KiB/s, done.
From https://github.com/ArduPilot/ardupilot
 * branch                  master     -> FETCH_HEAD
   cda2e0f30c..7a6f2c8e28  master     -> origin/master
Fetching submodule modules/waf
From https://github.com/ArduPilot/waf
   51f1529b..1b1625b8  master         -> origin/master
 * [new branch]        pr-python-3.11 -> origin/pr-python-3.11
Updating cda2e0f30c..7a6f2c8e28
Fast-forward
 modules/waf | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
andre@Loke:~/prog/ardupilot$ ./waf 
Traceback (most recent call last):
  File "/home/andre/prog/ardupilot/modules/waf/waf-light", line 167, in <module>
    Scripting.waf_entry_point(cwd, VERSION, wafdir)
  File "/home/andre/prog/ardupilot/modules/waf/waflib/Scripting.py", line 80, in waf_entry_point
    env.load(os.path.join(cur, Options.lockfile))
  File "/home/andre/prog/ardupilot/modules/waf/waflib/ConfigSet.py", line 315, in load
    code = Utils.readf(filename, m='rU')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andre/prog/ardupilot/modules/waf/waflib/Utils.py", line 231, in readf
    with open(fname, m) as f:
         ^^^^^^^^^^^^^^
ValueError: invalid mode: 'rUb'

```

**Comment by AndKe** [comment]
there are two more possible offenders:

andre@Loke:~/prog/ardupilot/modules/waf/waflib$ grep -inr "m='rU'"
Context.py:665:		code = Utils.readf(path, m='rU', encoding=encoding)
ConfigSet.py:315:		code = Utils.readf(filename, m='rU')

**Comment by AndKe** [comment]
@peterbarker  ...would you like a PR?
