### ISSUE TITLE
SITL: Could not link plane HITL binary for SpeedyBee F405 Wing

### ISSUE THREAD

**Issue by knoppixmeister** [ArduPilot/ardupilot#27534]
As continuation of https://github.com/ArduPilot/ardupilot/issues/27260 could not link final binary file for SpeedyBee F405 Wing. Compilation seems goes well but can not link.

Issued command:
```
./Tools/scripts/sitl-on-hardware/sitl-on-hw.py --board SpeedyBeeF405Wing --vehicle plane 
```

But can compile HITL for MatekH743, Matek F405-TE and Matek F405-Wing

Some final output:
```
[1150/1156] Linking build/SpeedyBeeF405WING/bin/arduplane
/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld:common.ld:202 cannot move location counter backwards (from 0000000008109c20 to 0000000008100000)
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/knoppix/Desktop/ardupilot/build/SpeedyBeeF405WING'
Build failed
 -> task in 'bin/arduplane' failed (exit status 1): 
	{task 133596514118784: cxxprogram AP_Arming.cpp.51.o,AP_ExternalControl_Plane.cpp.51.o,ArduPlane.cpp.51.o,Attitude.cpp.51.o,GCS_Mavlink.cpp.51.o,GCS_Plane.cpp.51.o,Log.cpp.51.o,Parameters.cpp.51.o,Plane.cpp.51.o,RC_Channel.cpp.51.o,VTOL_Assist.cpp.51.o,afs_plane.cpp.51.o,altitude.cpp.51.o,avoidance_adsb.cpp.51.o,commands.cpp.51.o,commands_logic.cpp.51.o,control_modes.cpp.51.o,ekf_check.cpp.51.o,events.cpp.51.o,failsafe.cpp.51.o,fence.cpp.51.o,is_flying.cpp.51.o,mode.cpp.51.o,mode_LoiterAltQLand.cpp.51.o,mode_acro.cpp.51.o,mode_auto.cpp.51.o,mode_autotune.cpp.51.o,mode_avoidADSB.cpp.51.o,mode_circle.cpp.51.o,mode_cruise.cpp.51.o,mode_fbwa.cpp.51.o,mode_fbwb.cpp.51.o,mode_guided.cpp.51.o,mode_loiter.cpp.51.o,mode_manual.cpp.51.o,mode_qacro.cpp.51.o,mode_qautotune.cpp.51.o,mode_qhover.cpp.51.o,mode_qland.cpp.51.o,mode_qloiter.cpp.51.o,mode_qrtl.cpp.51.o,mode_qstabilize.cpp.51.o,mode_rtl.cpp.51.o,mode_stabilize.cpp.51.o,mode_takeoff.cpp.51.o,mode_thermal.cpp.51.o,mode_training.cpp.51.o,motor_test.cpp.51.o,navigation.cpp.51.o,parachute.cpp.51.o,qautotune.cpp.51.o,quadplane.cpp.51.o,radio.cpp.51.o,reverse_thrust.cpp.51.o,sensors.cpp.51.o,servos.cpp.51.o,soaring.cpp.51.o,system.cpp.51.o,tailsitter.cpp.51.o,takeoff.cpp.51.o,tiltrotor.cpp.51.o,tuning.cpp.51.o -> arduplane}
 (run with -v to display more information)
Running (./waf configure --board=SpeedyBeeF405Wing --extra-hwdef=/tmp/tmp1nln51vl --default-param=/tmp/tmpsxkvlxsy)
Running (./waf plane)
FAILED: ./waf plane
Traceback (most recent call last):
  File "/home/knoppix/Desktop/ardupilot/./Tools/scripts/sitl-on-hardware/sitl-on-hw.py", line 87, in <module>
    run_program(build_cmd)
  File "/home/knoppix/Desktop/ardupilot/./Tools/scripts/sitl-on-hardware/sitl-on-hw.py", line 34, in run_program
    os.unlink(extra_hwdef.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp1nln51vl'

```

**Version**
git main

**Platform**

Ubuntu 24.04

[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
plane

**Hardware type**
SpeedyBee F405 Wing

**Logs**
[full_log.txt](https://github.com/user-attachments/files/16182675/full_log.txt)

**Comment by IamPete1** [comment]
You ran out of flash, you will have to turn off some features to make more room.
