### ISSUE TITLE
fly.QuadPlane build step is breaking Travis

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/ardupilot#3748]
>>>> RUNNING STEP: fly.QuadPlane at Wed Mar  9 12:06:38 2016
Running: /home/travis/build/diydrones/ardupilot/tmp/ArduPlane.build/ArduPlane.elf -w -S --home=-27.274439,151.290064,343,8.7 --model=quadplane --speedup=10.000000 --defaults=/home/travis/build/diydrones/ardupilot/Tools/autotest/quadplane.parm
Started model quadplane at -27.274439,151.290064,343,8.7 at speed 10.0
Starting sketch 'ArduPlane'
Starting SITL input
bind port 5760 for 0
Serial port 0 on TCP port 5760
Waiting for connection ....
Connect tcp:127.0.0.1:5760 source_system=255
Failed to load module: No module named terrain. Use 'set moddebug 3' in the MAVProxy console to enable traceback
no script test.QuadPlane/mavinit.scr
Log Directory: test.QuadPlane/logs/2016-03-09/flight1
Telemetry log: test.QuadPlane/logs/2016-03-09/flight1/flight.tlog
LOGFILE test.QuadPlane/logs/2016-03-09/flight1/flight.tlog
buildlog=/home/travis/build/diydrones/buildlogs/QuadPlane-test.tlog
MAV> Waiting for heartbeat from tcp:127.0.0.1:5760
Timed out looking for Received [0-9]+ parameters
>>>> FAILED STEP: fly.QuadPlane at Wed Mar  9 12:07:41 2016 (60)
Traceback (most recent call last):
  File "Tools/autotest/autotest.py", line 405, in run_tests
    if not run_step(step):
  File "Tools/autotest/autotest.py", line 237, in run_step
    return quadplane.fly_QuadPlane(viewerip=opts.viewerip, map=opts.map)
  File "/home/travis/build/diydrones/ardupilot/Tools/autotest/quadplane.py", line 75, in fly_QuadPlane
    mavproxy.expect('Received [0-9]+ parameters')
  File "/home/travis/build/diydrones/ardupilot/Tools/autotest/pysim/util.py", line 178, in _expect_callback
    raise pexpect.TIMEOUT(timeout)
TIMEOUT: 60
('check step: ', 'fly.QuadPlane')
FAILED 1 tests: ['fly.QuadPlane']
The command "Tools/scripts/build_ci.sh" exited with 1.

**Comment by magicrub** [comment]
this is fixed, old news
