### ISSUE TITLE
FPE when running autotest.py with build.Helicopter and fly.ArduCopter

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/ardupilot#4180]
#### Issue details
Floating point exception encountered on master when using autotest.py

#### Version
master (5461002eea9592dbb6933fd5a23f0e95e3ec630d)

#### Platform
- [ ] All
- [ ] AntennaTracker
- [*] Copter
- [ ] Plane
- [ ] Rover

#### Airframe type
heli 

#### Hardware type
SITL

#### Logs

```
pbarker@bluebottle:~/rc/ardupilot(master)$ ./Tools/autotest/autotest.py fly.ArduCopter^C
pbarker@bluebottle:~/rc/ardupilot(master)$ "/home/pbarker/rc/ardupilot/modules/waf/waf-light" "clean"
'clean' finished successfully (1.019s)
pbarker@bluebottle:~/rc/ardupilot(master)$ ./Tools/autotest/autotest.py build.HeliCopter
.
.
>>>> PASSED STEP: build.Helicopter at Sat May 21 13:56:46 2016
('check step: ', 'build.Helicopter')
pbarker@bluebottle:~/rc/ardupilot(master)$  
pbarker@bluebottle:~/rc/ardupilot(master)$ ./Tools/autotest/autotest.py fly.ArduCopter
>>>> RUNNING STEP: fly.ArduCopter at Sat May 21 13:57:21 2016
Running: /home/pbarker/rc/ardupilot/tmp/ArduCopter.build/ArduCopter.elf -w -S --home=-35.362938,149.165085,584,270 --model=+ --speedup=5.000000
Started model + at -35.362938,149.165085,584,270 at speed 5.0
.
.
param load /home/pbarker/rc/ardupilot/Tools/autotest/copter_params.parm
param load /home/pbarker/rc/ardupilot/Tools/autotest/copter_params.parm
STABILIZE> Saved 662 parameters to test.ArduCopter/logs/2016-05-21/flight21/mav.parm
fence breach
changed FRAME from 1.000000 to 0.000000
.
.
changed RC2_MIN from 1100.000000 to 1000.000000
changed RC3_MAX from 1900.000000 to 2000.000000
ERROR in command ['load', '/home/pbarker/rc/ardupilot/Tools/autotest/copter_params.parm']: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home/pbarker/.local/lib/python2.7/site-packages/MAVProxy-1.4.43-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 477, in process_stdin
.
.
  File "/home/pbarker/.local/lib/python2.7/site-packages/pymavlink-1.1.73-py2.7-linux-x86_64.egg/pymavlink/mavutil.py", line 900, in recv
    data = self.port.recv(n)
error: [Errno 104] Connection reset by peer
no link
link 1 down
no link



pbarker@bluebottle:~/rc/ardupilot(master)$ gdb --args /home/pbarker/rc/ardupilot/tmp/ArduCopter.build/ArduCopter.elf -w -S --home=-35.362938,149.165085,584,270 --model=+ --speedup=5.000000
GNU gdb (Ubuntu 7.11-0ubuntu1) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/pbarker/rc/ardupilot/tmp/ArduCopter.build/ArduCopter.elf...done.
(gdb) r
Starting program: /home/pbarker/rc/ardupilot/tmp/ArduCopter.build/ArduCopter.elf -w -S --home=-35.362938,149.165085,584,270 --model=+ --speedup=5.000000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Started model + at -35.362938,149.165085,584,270 at speed 5.0
Starting sketch 'ArduCopter'
Starting SITL input
bind port 5760 for 0
Serial port 0 on TCP port 5760
Waiting for connection ....
bind port 5762 for 2
Serial port 2 on TCP port 5762
bind port 5763 for 3
Serial port 3 on TCP port 5763

<<<<<<< mavproxy.py started in a separate shell, connecting on port 5760 >>>>>>>

Program received signal SIGFPE, Arithmetic exception.
Copter::send_location (this=0x7177a0 <copter>, chan=MAVLINK_COMM_0)
    at GCS_Mavlink.cpp:298
298	    mavlink_msg_global_position_int_send(
(gdb) bt
#0  Copter::send_location (this=0x7177a0 <copter>, chan=MAVLINK_COMM_0)
    at GCS_Mavlink.cpp:298
#1  0x000000000040ad3b in GCS_MAVLINK::try_send_message (
    this=this@entry=0x718f00 <copter+5984>, id=id@entry=MSG_LOCATION)
    at GCS_Mavlink.cpp:565
#2  0x0000000000428ba7 in GCS_MAVLINK::send_message (
    this=this@entry=0x718f00 <copter+5984>, id=id@entry=MSG_LOCATION)
    at /home/pbarker/rc/ardupilot/libraries/GCS_MAVLink/GCS_Common.cpp:872
#3  0x000000000040805a in GCS_MAVLINK::data_stream_send (this=<optimised out>)
    at GCS_Mavlink.cpp:905
#4  Copter::gcs_data_stream_send (this=<optimised out>) at GCS_Mavlink.cpp:2137
#5  0x00000000004c69af in Functor<void>::operator() (this=<optimised out>)
    at /home/pbarker/rc/ardupilot/libraries/AP_HAL/utility/functor.h:55
#6  AP_Scheduler::run (this=0x717ab8 <copter+792>, time_available=2500)
    at /home/pbarker/rc/ardupilot/libraries/AP_Scheduler/AP_Scheduler.cpp:141
#7  0x00000000004d189e in HAL_SITL::run (
    this=0x71b300 <AP_HAL::get_HAL()::hal>, argc=<optimised out>, 
    argv=<optimised out>, callbacks=0x7177a0 <copter>)
    at /home/pbarker/rc/ardupilot/libraries/AP_HAL_SITL/HAL_SITL_Class.cpp:95
#8  0x000000000040300e in main (argc=<optimised out>, argv=<optimised out>)
    at ArduCopter.cpp:623

(gdb) list
293	    } else {
294	        fix_time = millis();
295	    }
296	    const Vector3f &vel = inertial_nav.get_velocity();
297	    ::fprintf(stderr, "ahrs home alt is %ld\n", ahrs.get_home().alt);
298	    mavlink_msg_global_position_int_send(
299	        chan,
300	        fix_time,
301	        current_loc.lat,                // in 1E7 degrees
302	        current_loc.lng,                // in 1E7 degrees
(gdb) print vel
$2 = (const Vector3f &) @0x719934: {x = 7.03173296e+11, y = 2.80937968e+12, 
  z = 1.40627843e+12}
(gdb) print inertial_nav
$3 = {<AP_InertialNav> = {
    _vptr.AP_InertialNav = 0x4f42b0 <vtable for AP_InertialNav_NavEKF+16>}, 
  _relpos_cm = {x = 0, y = 0, z = -2.04018061e+09}, _velocity_cm = {
    x = 7.03173296e+11, y = 2.80937968e+12, z = 1.40627843e+12}, 
  _pos_z_rate = 3.50388322e+11, _abspos = {{flags = {relative_alt = 0 '\000', 
        unused1 = 0 '\000', loiter_ccw = 0 '\000', terrain_alt = 0 '\000', 
        origin_alt = 0 '\000', loiter_xtrack = 0 '\000'}, options = 0 '\000'}, 
    alt = 13, lat = -353629366, lng = 1491650837}, _haveabspos = true, 
  _ahrs_ekf = @0x718920}
```

(I've removed the "ahrs home alt" debug messages; they were all zero)

**Comment by peterbarker** [comment]
Paul's recent EKF work appears to have stopped the FPE from occurring.  Test really doesn't go well, but no FPE.
